-- MySQL Script generated by MySQL Workbench
-- Mon Jun 30 19:06:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_gestaoecontrole
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gestaoecontrole` DEFAULT CHARACTER SET utf8 ;
USE `db_gestaoecontrole` ;

-- -----------------------------------------------------
-- Table `db_gestaoecontrole`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gestaoecontrole`.`usuario` (
  `id` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_gestaoecontrole`.`tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_gestaoecontrole`.`tarefas` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `descricao` VARCHAR(225) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `criado_por` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarefas_usuario_idx` (`criado_por` ASC),
  CONSTRAINT `fk_tarefas_usuario`
    FOREIGN KEY (`criado_por`)
    REFERENCES `db_gestaoecontrole`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
